- name: Install basic apps
  ansible.builtin.apt:
    pkg:
      - vim 
      - tmux
      - net-tools
      - iputils-ping
      - apt-transport-https 
      - ca-certificates 
      - curl
      - jq
      - python3-jsonpath-rw
      - nfs-common
